#pragma config(Sensor, S1,     DIMC,           sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     inf1d,          sensorEV3_GenericI2C)
#pragma config(Sensor, S4,     inf2d,          sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          FL,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          FR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          BR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          BL,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3smux.h"

int Sshooting = 50;
int Saim = 50;
float mux[3];

void Mstop()   {motor[FL] = 0;  motor[FR] = 0;  motor[BR] = 0;  motor[BL] = 0;}
void Mforward(){motor[FL] = Sshooting; motor[FR] = Sshooting; motor[BR] = -Sshooting;motor[BL] = -Sshooting;}
void Tleft()   {motor[FL] = Saim; motor[FR] = Saim; motor[BR] = Saim; motor[BL] = Saim;}
void Tright()  {motor[FL] = -Saim;motor[FR] = -Saim;motor[BR] = -Saim;motor[BL] = -Saim;}

tMSEV3 muxedSensor[3];
tEV3SensorTypeMode typeMode[3] = {colorReflectedLight, colorReflectedLight, colorReflectedLight};

task main()
{
	eraseDisplay();
	if (!initSensor(&muxedSensor[0], msensor_S2_1, typeMode[0]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_1");

	if (!initSensor(&muxedSensor[1], msensor_S2_2, typeMode[1]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_2");

	if (!initSensor(&muxedSensor[2], msensor_S2_3, typeMode[2]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_3");
	while(true)
	{
		for (int i = 0; i < 3; i++)
		{
			if (!readSensor(&muxedSensor[i]))
				writeDebugStreamLine("readSensor() failed! for %d", i);

			switch(muxedSensor[i].typeMode)
			{
			case colorReflectedLight:
				mux[i] = muxedSensor[i].light;
				break;
			}
		}
		if(mux[0]>20){
			if(mux[2]>20){
					Mforward();
			}	else if(mux[2]<20){
				Tright();
			}
		} else if(mux[0]<20){
			if(mux[2]<20){
				Tleft();
			} else{
				Mstop();
			}
		}
		displayTextLine(1, "Value: %d", mux[0]);
		displayTextLine(4, "Value: %d", mux[1]);
		displayTextLine(7, "Value: %d", mux[2]);
	}
}
