#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "mindsensors-ev3smux.h"

tMSEV3 muxedSensor[3];
tEV3SensorTypeMode typeMode[3] = {colorReflectedLight, colorReflectedLight, colorReflectedLight};

task main()
{
	while(true){
		for (int i = 0; i < 3; i++)
		{
			switch(muxedSensor[i].typeMode)
			{
			case colorReflectedLight:
				isplayTextLine(i*3, "Chan[%d]: Ref Light", i+1);
				displayTextLine(i*3 + 1, "Value: %d", muxedSensor[i].light);
				break
			}
		}
	}
