#pragma config(Motor,  motorA,          FR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          BR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          BL,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          FL,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Sshooting = 100; //Shooting Speed

//Movement Functions
void Mforward(){motor[FR] = Sshooting;motor[BR] = Sshooting; 	motor[BL] = -Sshooting;	motor[FL] = -Sshooting;}

task main()
{
	while(1){
		Mforward();
	}
}
