#pragma config(Sensor, S1,     DIMC,           sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int comp;
int reflect;
int front;
int back;

task main()
{
	while(true)
	{
		comp = SensorValue(S1);
		reflect = SensorValue(S2);
		front = SensorValue(S3);
		back = SensorValue(S4);
		//Compass
		if(comp<=70 && comp>= 90)
		{
			setMotorSpeed(motorA, -20);
			setMotorSpeed(motorB, -20);
			setMotorSpeed(motorC, -20);
			setMotorSpeed(motorD, -20);
		}
		if(comp>=70 || comp<=90)
		{
			setMotorSpeed(motorA, -20);
			setMotorSpeed(motorB, 20);
			setMotorSpeed(motorC, 20);
			setMotorSpeed(motorD, -20);
		}
		/*Front Infrared Sensor
		if(front==5)
		{
		setMotorSpeed(motorA, -50);
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
		setMotorSpeed(motorD, -50);
		}
		if(front==0)
		{
		setMotorSpeed(motorA, 50);
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
		setMotorSpeed(motorD, 50);
		}
		if(front>=7)
		{
		setMotorSpeed(motorA, -50);
		setMotorSpeed(motorB, 50);
		setMotorSpeed(motorC, 50);
		setMotorSpeed(motorD, -50);
		}
		Back Infrared Sensor*/
	}
}
