#pragma config(Sensor, S1,     DIMC,           sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          FL,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          FR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          BR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          BL,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int comp;
task main()
{
	while(true)
	{
		comp = SensorValue(S1);

		if(comp>=100&&comp<=110)
		{
			motor[FL] = -20;
			motor[FR] = 20;
			motor[BR] = 20;
			motor[BL] = -20;
		}
		if(comp>110)
		{
			motor[FL] = 20;
			motor[FR] = 20;
			motor[BR] = 20;
			motor[BL] = 20;
		}
		if(comp<100)
		{
			motor[FL] = -20;
			motor[FR] = -20;
			motor[BR] = -20;
			motor[BL] = -20;
		}
	}
}
