#pragma config(Sensor, S1,     DIMC,           sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     inf1d,          sensorEV3_GenericI2C)
#pragma config(Sensor, S4,     inf2d,          sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          FL,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          FR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          BR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          BL,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3smux.h"
#include "hitechnic-irseeker-v2.h"

int goalcomp; //Goal Direction
int Sorbit = 100; //Orbit Speed
int Saim = 40; //Aiming speed
int range = 6; //Radius of Accuracy (The lower the better accuarcy)
int Sshooting = 100; //Shooting Speed
int comp,inf1,inf1s,inf2,inf2s,maxcomp,mincomp;
bool Rcomp;
float mux[3];

tMSEV3 muxedSensor[3];
tEV3SensorTypeMode typeMode[3] = {colorReflectedLight, colorReflectedLight, colorReflectedLight};

void Mstop()   {motor[FL] = 0;  motor[FR] = 0;  motor[BR] = 0;  motor[BL] = 0;}
void Mforward(){motor[FL] = Sshooting; motor[FR] = Sshooting; motor[BR] = -Sshooting;motor[BL] = -Sshooting;}
void Mright()  {motor[FL] = -Sorbit;motor[FR] = Sorbit; motor[BR] = Sorbit; motor[BL] = -Sorbit;}
void Mmright() {motor[FL] = -Saim;motor[FR] = Saim; motor[BR] = Saim; motor[BL] = -Saim;}
void Mleft()   {motor[FL] = Sorbit; motor[FR] = -Sorbit;motor[BR] = -Sorbit;motor[BL] = Sorbit;}
void Mmleft()  {motor[FL] = Saim; motor[FR] = -Saim;motor[BR] = -Saim;motor[BL] = Saim;}
void Mback()   {motor[FL] = -Sorbit;motor[FR] = -Sorbit;motor[BR] = Sorbit; motor[BL] = Sorbit;}
void Tleft()   {motor[FL] = Saim; motor[FR] = Saim; motor[BR] = Saim; motor[BL] = Saim;}
void Tright()  {motor[FL] = -Saim;motor[FR] = -Saim;motor[BR] = -Saim;motor[BL] = -Saim;}

task main()
{
	eraseDisplay();
	if (!initSensor(&muxedSensor[0], msensor_S2_1, typeMode[0]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_1");

	if (!initSensor(&muxedSensor[1], msensor_S2_2, typeMode[1]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_2");

	if (!initSensor(&muxedSensor[2], msensor_S2_3, typeMode[2]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_3");
	tHTIRS2 irSeeker1;
	tHTIRS2 irSeeker2;

	initSensor(&irSeeker1, inf1d);
	initSensor(&irSeeker2, inf2d);
	comp = SensorValue[S1];
	goalcomp = comp;
	mincomp = goalcomp - range;
	maxcomp = goalcomp + range;
	while(true)
	{
		if(inf1==0&&inf2==0&&Rcomp==true){
			Mstop();
		}
		if(mux[0]>5&&mux[2]>5){
			Mback();
		}
		else if(mux[0]>5){
			Mright();
		}
		else if(mux[1]>5){
			Mforward();
		}
		else if(mux[2]>5){
			Mleft();
		}
		readSensor(&irSeeker1);
		readSensor(&irSeeker2);
		comp = SensorValue[S1];
		inf1 = irSeeker1.acDirection;
		inf2 = irSeeker2.acDirection;
		inf1s = irSeeker1.enhStrength;
		inf2s = irSeeker2.enhStrength;
		for (int i = 0; i < 3; i++)
		{
			if (!readSensor(&muxedSensor[i]))
				writeDebugStreamLine("readSensor() failed! for %d", i);

			switch(muxedSensor[i].typeMode)
			{
			case colorReflectedLight:
				/*displayTextLine(i*3, "Chan[%d]: Ref Light", i+1);
				displayTextLine(i*3 + 1, "Value: %d", muxedSensor[i].light);*/
				mux[i] = muxedSensor[i].light;
				break;
			}
		}

		/*displayTextLine(1, "Value: %d", mux[0]);
		displayTextLine(4, "Value: %d", mux[1]);
		displayTextLine(7, "Value: %d", mux[2]);
		displayTextLine(10,"Inf1: %i",inf1);
		displayTextLine(11,"Inf1s: %i",inf1s);
		displayTextLine(12,"Inf2: %i",inf2);
		displayTextLine(13,"Inf2s: %i",inf2s);
		displayTextLine(14,"Comp: %i",comp);*/
		if(comp>=mincomp&&comp<=maxcomp){
			Rcomp = true;
			if(inf1s<inf2s){
				if(inf2>5&&inf2<9)
				{
					Mleft();
				}
				if(inf2<6)
				{
					Mright();
				}
				if(inf2<4&&inf2>0)
				{
					Mback();
				}
				if(inf2>6&&inf2<10)
				{
					Mback();
				}
			}
			if(inf1s>inf2s)
			{
				if(inf1>=3&&inf1<=4)
				{
					Mmleft();
				}
				if(inf1>=6&&inf1<=7)
				{
					Mmright();
				}
				if(inf1==5)
				{
					Mforward();
				}
			}
		}
		if((comp<mincomp)||((comp>maxcomp+82))){
			Tright();
			Rcomp = false;
		} else if((comp<maxcomp+82)&&(comp>maxcomp)){
			Tleft();
			Rcomp = false;
		}
		if(((comp<mincomp-82))||(comp>maxcomp)){
			Tleft();
			Rcomp = false;
		} else if((comp>mincomp-82)&&(comp<mincomp)){
			Tright();
			Rcomp = false;
		}
		/*if(mincomp<90){
			if(comp>maxcomp&&comp<maxcomp+90)
			{
				Rcomp = false;
				Tleft();
			}
			if(comp<mincomp||comp>maxcomp+90)
			{
				Rcomp = false;
				Tright();
			}
		}
		else if(mincomp>90){
			if(comp>maxcomp||comp<mincomp-90)
			{
				Rcomp = false;
				Tleft();
			}
			if(comp<mincomp&&comp>mincomp-90)
			{
				Rcomp = false;
				Tright();
			}
		}*/
	}
}
