#pragma config(Sensor, S1,     DIMC,           sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     inf1d,          sensorEV3_GenericI2C)
#pragma config(Sensor, S4,     inf2d,          sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          FL,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          FR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          BR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          BL,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-ev3smux.h"
#include "hitechnic-irseeker-v2.h"
int comp;
int inf1;
int inf1s;
int inf2;
int inf2s;
//int stopp;
tMSEV3 muxedSensor[3];
tEV3SensorTypeMode typeMode[3] = {colorReflectedLight, colorReflectedLight, colorReflectedLight};

void Mstop()
{
	motor[FL] = 50;
	motor[FR] = 50;
	motor[BR] = -50;
	motor[BL] = -50;
}
void Mforward()
{
	motor[FL] = 50;
	motor[FR] = 50;
	motor[BR] = -50;
	motor[BL] = -50;
}
void Mright()
{
	motor[FL] = -50;
	motor[FR] = 50;
	motor[BR] = 50;
	motor[BL] = -50;
}
void Mleft()
{
	motor[FL] = 50;
	motor[FR] = -50;
	motor[BR] = -50;
	motor[BL] = 50;
}
void Mback()
{
	motor[FL] = -50;
	motor[FR] = -50;
	motor[BR] = 50;
	motor[BL] = 50;
}
void Tleft()
{
	motor[FL] = 30;
	motor[FR] = 30;
	motor[BR] = 30;
	motor[BL] = 30;
}
void Tright()
{
	motor[FL] = -30;
	motor[FR] = -30;
	motor[BR] = -30;
	motor[BL] = -30;
}
task main()
{
  eraseDisplay();
  if (!initSensor(&muxedSensor[0], msensor_S2_1, typeMode[0]))
  	writeDebugStreamLine("initSensor() failed! for msensor_S2_1");

  if (!initSensor(&muxedSensor[1], msensor_S2_2, typeMode[1]))
  	writeDebugStreamLine("initSensor() failed! for msensor_S2_2");

  if (!initSensor(&muxedSensor[2], msensor_S2_3, typeMode[2]))
  	writeDebugStreamLine("initSensor() failed! for msensor_S2_3");
	tHTIRS2 irSeeker1;
	tHTIRS2 irSeeker2;

	initSensor(&irSeeker1, inf1d);
	initSensor(&irSeeker2, inf2d);
	while(true)
	{
		for (int i = 0; i < 3; i++)
 		{
			if (!readSensor(&muxedSensor[i]))
				writeDebugStreamLine("readSensor() failed! for %d", i);

 			switch(muxedSensor[i].typeMode)
 			{
		 		case colorReflectedLight:
					displayTextLine(i*3, "Chan[%d]: Ref Light", i+1);
					displayTextLine(i*3 + 1, "Value: %d", muxedSensor[i].light);
		 			break;
		  }
		  displayTextLine(i*3 +2, " ");
 		}
		readSensor(&irSeeker1);
		readSensor(&irSeeker2);
		comp = SensorValue[S1];
		inf1 = irSeeker1.acDirection;
		inf2 = irSeeker2.acDirection;
		inf1s = irSeeker1.enhStrength;
		inf2s = irSeeker2.enhStrength;
		if(comp>=60&&comp<80)
		{
			if(inf1==0&&inf2==0){
				Mstop();
			}
			if(inf1s<inf2s){
				if(inf2>5&&inf2<9)
				{
					Mleft();
				}
				if(inf2<6)
				{
					Mright();
				}
				if(inf2<4&&inf2>0)
				{
					Mback();
				}
				if(inf2>6&&inf2<9)
				{
					Mback();
				}
			}
			if(inf1s>inf2s)
			{
				if(inf1>=2&&inf1<=3)
				{
					Mleft();
				}
				if(inf1>=8&&inf1<=9)
				{
					Mright();
				}
				if(inf1==5)
				{
					Mforward();
				}
			}
		}
		if(comp>80&&comp<160)
		{
			Tleft();
		}
		if(comp<60||comp>160)
		{
			Tright();
		}
	}
}
