#pragma config(Sensor, S1,     DIMC,           sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     inf1d,          sensorEV3_GenericI2C)
#pragma config(Sensor, S4,     inf2d,          sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          FL,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          FR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          BR,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          BL,            tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "mindsensors-ev3smux.h"
#include "hitechnic-irseeker-v2.h"
int comp;
int inf1;
int inf1s;
int inf2;
int inf2s;

task main()
{
	tHTIRS2 irSeeker1;
	tHTIRS2 irSeeker2;

	initSensor(&irSeeker1, inf1d);
	initSensor(&irSeeker2, inf2d);
	while(true)
	{
		readSensor(&irSeeker1);
		readSensor(&irSeeker2);
		comp = SensorValue[S1];
		inf1 = irSeeker1.acDirection;
		inf2 = irSeeker2.acDirection;
		inf1s = irSeeker1.enhStrength;
		inf2s = irSeeker2.enhStrength;
		if(comp>=10&&comp<30)
		{
			if(inf1==0&&inf2==0){
				motor[FL] = 0;
				motor[FR] = 0;
				motor[BR] = 0;
				motor[BL] = 0;
			}
			if(inf1s<inf2s){
				if(inf2>5&&inf2<9)
				{
					motor[FL] = 50;
					motor[FR] = -50;
					motor[BR] = -50;
					motor[BL] = 50;
				}
				if(inf2<6)
				{
					motor[FL] = -50;
					motor[FR] = 50;
					motor[BR] = 50;
					motor[BL] = -50;
				}
				if(inf2<4&&inf2>0)
				{
					motor[FL] = -50;
					motor[FR] = -50;
					motor[BR] = 50;
					motor[BL] = 50;
				}
				if(inf2>6&&inf2<9)
				{
					motor[FL] = -50;
					motor[FR] = -50;
					motor[BR] = 50;
					motor[BL] = 50;
				}
			}
			if(inf1s>inf2s)
			{
				if(inf1>=2&&inf1<=3)
				{
					motor[FL] = 50;
					motor[FR] = -50;
					motor[BR] = -50;
					motor[BL] = 50;
				}
				if(inf1>=8&&inf1<=9)
				{
					motor[FL] = -50;
					motor[FR] = 50;
					motor[BR] = 50;
					motor[BL] = -50;
				}
				if(inf1==5)
				{
					motor[FL] = 50;
					motor[FR] = 50;
					motor[BR] = -50;
					motor[BL] = -50;
				}
			}
		}
		if(comp>30&&comp<100)
		{
			motor[FL] = 30;
			motor[FR] = 30;
			motor[BR] = 30;
			motor[BL] = 30;
		}
		if(comp<10||comp>=100)
		{
			motor[FL] = -30;
			motor[FR] = -30;
			motor[BR] = -30;
			motor[BL] = -30;
		}
	}
}
