#pragma config(Sensor, S2,     ,               sensorEV3_GenericI2C)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "mindsensors-ev3smux.h"

tMSEV3 muxedSensor[3];
tEV3SensorTypeMode typeMode[3] = {colorReflectedLight,colorReflectedLight,colorReflectedLight};

task main()
{
	if (!initSensor(&muxedSensor[0], msensor_S2_1, typeMode[0]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_1");

	if (!initSensor(&muxedSensor[1], msensor_S2_2, typeMode[1]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_2");

	if (!initSensor(&muxedSensor[2], msensor_S2_3, typeMode[2]))
		writeDebugStreamLine("initSensor() failed! for msensor_S2_3");
	while(true){
		for(int i=0;i<3;i++){
			if (!readSensor(&muxedSensor[i]))
				writeDebugStreamLine("readSensor() failed! for %d", i);

			switch(muxedSensor[i].typeMode)
			{
			case colorReflectedLight:
				displayTextLine(i*3, "Chan[%d]: Ref Light", i+1);
				displayTextLine(i*3 + 1, "Value: %d", muxedSensor[i].light);
				break;
			}
		}
	}
}
